extends:
  - react-app
  - eslint:recommended
  - plugin:react/recommended
  - airbnb
plugins:
  - react
settings:
  react:
    version: detect
rules:
  no-console: [2, { "allow": ["warn", "error"]}]
