extends:
  - react-app
  - eslint:recommended
  - plugin:react/recommended
  - airbnb
plugins:
  - react
settings:
  react:
    version: detect
rules:
  no-console: [2, { "allow": ["warn", "error"]}]
  react/jsx-filename-extension: [0]  # Imports don't work if I change extension.
  react/sort-comp: [0]  # Non-alphabetical groupings can make more sense.
