sudo: false

language: node_js
node_js:
  - 13

# Fix build failure.
# https://github.com/cypress-io/cypress/issues/4069#issuecomment-488315675
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    # I think it defaults to this:
    - node_modules
    # Default if "npm ci" were the script, but non-empty, so include it explicitly:
    - ~/.npm
    # Cypress binary is here:
    - ~/.cache

before_script:
  # https://stackoverflow.com/a/59572966
  - export NODE_OPTIONS=--max_old_space_size=4096
script:
  - ./test.sh

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      branch: master
