sudo: false

language: node_js
node_js:
  - 8

cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    - ~/.npm
    # we also need to cache folder with Cypress binary
    - ~/.cache

script:
  - ./test.sh
  # TODO: Do these contain anything?
  - ls ~/.npm
  - ls ~/.cache
