name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install NPM dependencies
        run: npm ci
      - name: Run tests
        run: ./test.sh
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
      - name: Deploy to NPM
        run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}