# Adapted from https://github.com/vega/vega/blob/4b945e22905c610ccc2bdd28471a6f1f80aa1636/.github/workflows/test.yml
name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14]
        os: [ubuntu-18.04]
        include:
          - os: windows-2019
            node: 14
    
    name: Test on ${{ matrix.os }} with Node ${{ matrix.node }}
    
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install NPM dependencies
        run: npm ci
      - name: Install dependencies needed for testing with cypress
        run: | # needed for cypress on linux github actions
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install xvfb
          fi
        shell: bash
      - name: Run tests
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              xvfb-run --auto-servernum ./test.sh
          elif [ "$RUNNER_OS" == "Windows" ]; then
              ./test.sh
          fi
        shell: bash
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        