# Adapted from https://github.com/vega/vega/blob/4b945e22905c610ccc2bdd28471a6f1f80aa1636/.github/workflows/test.yml
name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14]
        os: [ubuntu-18.04]
        include:
          - os: windows-2019
            node: 14
    
    name: Test on ${{ matrix.os }} with Node ${{ matrix.node }}
    
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install NPM dependencies
        run: npm ci
      - name: Install dependencies needed for testing with cypress on Linux
        run: sudo apt-get install xvfb # needed for cypress
        if: runner.os == 'Linux'
      - name: Run tests (Linux)
        run: xvfb-run --auto-servernum ./test.sh
        if: runner.os == 'Linux'
      - name: Run tests (Windows)
        run: ./test.sh
        if: runner.os == 'Windows'
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
        